#create cuda9.0 pytorch 1.4.0 tochvision 0.5.0 docker file

# cuda9.0

# install ros

# create venv with pytorch 0.4.0 torchvision 0.2.0 inside docker
# install pytorch 0.4.0
wget https://download.pytorch.org/whl/cu90/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
pip install torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
