#create cuda9.0 pytorch 1.4.0 tochvision 0.5.0 docker file

# cuda9.0

# install ros

# install miniconda and 
cd ~
wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
mkdir /root/.conda
bash Miniconda2-latest-Linux-x86_64.sh -b

# Edit .bashrc to resolve conflict with ROS

# Setup pytorch 0.4.0 environment for mattnet and vmrn_old
conda create -n pytorch_old python=2.7
pip install torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
